version: '3'
services:
  jobspro:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:
     - jobspro:/jobspro/dist/  # build files will be added at this directory !!!

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - jobspro:/usr/share/nginx/html/jobspro # Copy React App's build files to the Nginx directory

volumes:
   jobspro:

