version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    cache_from:
        - '${JOBSPRO_IMAGE}'
    image: '${JOBSPRO_IMAGE}'
    ports:
      - "8080:8080"
    volumes:
      - website:./jobspro/build/  # build files will be added at this directory !!!

  nginx:
    build:
     context: ./nginx
     dockerfile: Dockerfile
    cache_from:
        - '${NGINX_IMAGE}'
    image: '${NGINX_IMAGE}'
    ports:
      - "80:80"
    volumes:
      - website:/usr/share/nginx/html/jobspro # Copy React App's build files to the Nginx directory